Add files via upload
'''
Попытайтесь изменить элементы кортежа immutable_var. Объясните, почему нельзя изменить значения элементов кортежа.
_________________________
  immutable_var = 1, 2, True, "Some string"
print(immutable_var)
immutable_var[0]= 30
__________________________
OUTPUT
(1, 2, True, 'Some string')
Traceback (most recent call last):

    immutable_var[0]= 30
    ~~~~~~~~~~~~~^^^
TypeError: 'tuple' object does not support item assignment
______________________________
объяснение пункта 3:

Кортежи являются неизменяемыми объектами, что означает, что вы не можете изменить их
 после создания. Если вы попытаетесь изменить кортеж на месте, используя оператор индексации[],
 вы вызовете ошибку  не поддерживает назначение элемента.
_______________________________

4. Создание изменяемых структур данных:
  - Создайте переменную mutable_list и присвойте ей список из нескольких элементов.
  - Измените элементы списка mutable_list.
  - Выведите на экран измененный список mutable_list.'''

mutable_list =[1, 2, True, 'Some string']
mutable_list[0]=30
print(mutable_list )